Update pyth and withdraw draft
Pando-Infinity/xlend-smart-contract-sui pull request #6
Opened 2024-06-09 09:11 UTC by Babybluess

2024-06-13 06:17 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +    const DEFAULT_RATE_FACTOR: u64 = 10000;
duplicated

2024-06-13 06:17 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +    const SUI_COIN_TYPE: vector<u8> = b"0x587c29de216efd4219573e08a1f6964d4fa7cb714518c2c8a0f29abfa264327d";
redundant?

2024-06-13 06:17 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        assert!(is_valid_collateral(lend_amount, configuration, collateral_amount, 0,
format code, too long

2024-06-13 06:17 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +    public entry fun is_valid_collateral(
is_valid_collateral_amount
or
check_health_ratio

2024-06-13 06:17 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        clock: &Clock,
comment: clock should move to end, before context (ctx)

2024-06-13 06:17 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        let remaining_collateral_price_total = get_price_total(clock, pyth_state, price_info_object_collateral, remaining_collateral_amount, time_threshhold);
get_value_by_usd

2024-06-13 06:17 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +    fun get_price_total (
move all price function to other module, such as PriceFeed

2024-06-13 06:17 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        price_value
what is unit of price_value here?
https://docs.pyth.network/price-feeds/best-practices

2024-06-13 06:39 UTC, pando-dreamer requested changes

2024-06-13 06:39 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        let _tier_id = offer::get_tier_id<T1>(offer);
why not tier_id?

2024-06-13 06:39 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +    public entry fun is_valid_collateral(
hàm này để private thôi

2024-06-13 06:39 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        withdraw_amount: u64,
mục tiêu là check health ratio, bỏ input withdraw amount

2024-06-13 06:39 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        let current_health_ratio = remaining_collateral_price_total / lend_price_total;
Cần tính cả decimals của từng loại coin ở đây

2024-06-13 06:39 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        offer_id: ID,
No need offer_id here, can get from Loan data

2024-06-13 06:39 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        assert!(state::contain<OfferKey<T1>, Offer<T1>>(state, offer_key), EOfferNotFound);
should check loan is valid here than check offer

2024-06-13 06:39 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        price_info_object_collateral: &PriceInfoObject,
Need to check PriceInfoObject is valid (for type T1/T2) or not

2024-06-14 10:07 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +     public entry fun withdraw_collateral_loan_offer<T1, T2>(
- version, configuration, state
- loan_id, withdraw_amount --> loan
- coin_metadata
- pyth objects

2024-06-14 10:09 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        configuration: &Configuration,
tương tự withdraw, thiếu version, thống nhất lại về thứ tự params

2024-06-14 10:09 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        deposit_coin: Coin<T2>,
deposit_amount

2024-06-14 10:10 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        let _lend_fee_percentage = configuration::lender_fee_percent(configuration);
lend_fee_percentage

2024-06-14 10:11 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        let _status = string::utf8(MATCHED_STATUS);
check contract status: only in status FUND_TRANSFERRED

2024-06-14 10:12 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        let loan = state::borrow_mut<LoanKey<T1, T2>, Loan<T1, T2>>(state, loan_key);
need check contract status

2024-06-14 10:13 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +        let _status = string::utf8(MATCHED_STATUS);
get status contract

2024-06-18 03:18 UTC, pando-dreamer requested changes

2024-06-18 03:18 UTC, pando-dreamer commented on lending_contract/sources/utils.move
> +            result
thừa

2024-06-18 03:18 UTC, pando-dreamer commented on lending_contract/sources/loan.move
> +     public entry fun withdraw_collateral_loan_offer<T1, T2>(
Vẫn thiếu version, chưa check loan status

2024-06-18 11:41 UTC, pando-dreamer requested changes

2024-06-18 11:41 UTC, pando-dreamer commented on lending_contract/sources/offer.move
> +    public fun get_asset_tier<T>(
duplicate with get_tier_id?

2024-06-18 11:41 UTC, pando-dreamer commented on lending_contract/sources/utils.move
> +        if (!is_negative) {
return is_negative

2024-06-18 11:41 UTC, pando-dreamer commented on lending_contract/sources/price_feed.move
> +        let value_usd = price_usd * ((amount * utils::power(10, sub_decimals) / exponent_power) as u128);
wrong calculation

2024-06-19 06:58 UTC, ducbtsn commented on lending_contract/sources/price_feed.move
> +            value_usd = ((price_u64 * amount_by_max_decimals / exponent_power) as u128);
may cause overflow here

2024-06-19 06:58 UTC, ducbtsn commented on lending_contract/sources/price_feed.move
> +        let amount_by_max_decimals = amount * utils::power(10, max_decimals) / utils::power(10, (coin_decimals_u8 as u64));
may cause overflow here

2024-06-19 07:58 UTC, merged